AWSTemplateFormatVersion: '2010-09-09'
Description: "Media Insights Engine - Workflow to run Rekognition"

Parameters:
  StepfunctionRoleArn:
    Type: String
  WorkflowCustomResourceArn:
    Type: String
    Description: "ARN of the Media Insights custom resource that handles creating operations, stages and workflows"
  CelebRecognitionImage:
    Type: String
  ContentModerationImage:
    Type: String
  FaceDetectionImage:
    Type: String
  FaceSearchImage:
    Type: String
  LabelDetectionImage:
    Type: String

Resources:
# Stages

  RekognitionStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "RekognitionStage"
      Operations:
        - !Ref CelebRecognitionImage
        - !Ref ContentModerationImage
        - !Ref FaceDetectionImage
        - !Ref FaceSearchImage
        - !Ref LabelDetectionImage
  
  # Workflows

  ImageWorkflow:
    DependsOn:
      - RekognitionStage
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Workflow"
      RoleArn: !Ref StepfunctionRoleArn
      Name: "ImageWorkflow"
      Stages: !Sub
        - |-
          {
            "${rekognitionSuite}":
            {
              "End": true
            }
          }
        - {
          rekognitionSuite: !GetAtt RekognitionStage.Name
        }
      StartAt: !GetAtt RekognitionStage.Name

